datahub/urls.py
from organization.admin import datahub_admin_site
from django.urls import path, include

urlpatterns = [
    path('', include('maintenance.urls')),
    path('admin/', datahub_admin_site.urls ),
]

maintenance/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('dashboard/<str:owner_id>', views.dashboard, name='dashboard'),

#    path('addscopes/<str:application_key>', views.AddScopesView.as_view(), name='addscopes'),
    
    path('setareascope', views.setareascope, name='setareascope'),
    path('setareascope/<str:areascope_id>', views.setareascope, name='setareascope'),
    
    path('load', views.load, name='load'),

    path('check', views.check, name='check'),
    path('checkowner/<str:owner_id>', views.checkowner, name='checkowner'),
    path('checkapplication/<str:application_id>', views.checkapplication, name='checkapplication'),

    path('area-rls/<str:area_id>', views.area_rls, name='area_rls'),

    path('switch_user/<int:user_id>', views.switch_user, name='switch_user'),
]

maintenance/models.py
from django.db import models

# Create your models here.

organization/models.py
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.core import serializers
from django.db import models, connections
from django.contrib.auth.models import AbstractUser, Group
from datahub.settings import LANGUAGES, HUB_OWNER_KEY, HUB_APPLICATION_KEY, DATABASES
from django.utils.translation import gettext as _
from django.db.models.signals import post_save, post_delete, m2m_changed
from django.dispatch import receiver
import uuid
import logging

db_logger = logging.getLogger('data')


PERMISSION_DIRECT_ACCESS = "db_read_access"
PERMISSION_UPLOAD_TEMPLATES = "upload_templates"
PERMISSION_DOWNLOAD_TEMPLATES = "download_templates"


class AbstractDatahubModel(models.Model):
    """ Default definition of all DATA-Hub objects
    """

    class Meta:
        abstract = True

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    active = models.BooleanField(_('active'), null=False, default=True,
                                 help_text=_("Inactive object is not available for end users"))

    desc = models.CharField(_('desc'), max_length=80, null=True, blank=True)
    text = models.TextField(_('text'), null=True, blank=True)

    ctime = models.DateTimeField(_('Create Time'), null=True, blank=True, )
    cuser = models.CharField(_('Create User'), max_length=8, null=True, blank=True,)
    utime = models.DateTimeField(_('Update Time'), null=True, blank=True, )
    uuser = models.CharField(_('Update User'), max_length=8, null=True, blank=True, )

    @classmethod
    def serialize(cls, objects):
        """
        Das Serialisieren wird für Migrationen bzw. Unload verwendet. 
        Wird in einen 'Umschlag' mit Signator und QuellenAngaben gepackt.
        https://docs.djangoproject.com/en/5.0/topics/serialization/#serializing-django-objects

        Zu beachten: Performance 
        https://www.django-rest-framework.org/api-guide/relations/
        """
        return serializers.serialize("jsonl", objects)

    @classmethod
    def deserialize(cls, data):
        """
        Das Deserialisieren wird für Migrationen bzw. Load verwendet. 
        https://docs.djangoproject.com/en/5.0/topics/serialization/#deserialization-of-natural-keys
        Zu beachten: Fremdschlüssel-Handling
        """
        serie = serializers.deserialize("jsonl", data)
        count = 0
        for deserialized_object in serie:
            try:
                deserialized_object.save()
                count += 1
            except Exception as e:
                print(deserialized_object, e) 
        return count


    def __str__(self):
        """ Field 'Key' has to be defined in derived class
        """
        return f'{self.key}'


class Owner(AbstractDatahubModel):
    """ Used to assign ownership to applications and container.
        A owner might be owned by an other organization
    """
    class Meta:
        verbose_name = _("Owner")
        verbose_name_plural = _("Owners")
        ordering = ['key']
        permissions = [
            ("view_dashboard", "Can view Dashboard"),
        ]

    __hub = None

    owner = models.ForeignKey(
        'Owner', on_delete=models.PROTECT, null=True, blank=True, related_name='+',)
    key = models.CharField(_('key'), max_length=20, unique=True,)
    kanton = models.CharField(_('kanton'), max_length=2, null=True, blank=True)
    nr = models.IntegerField(_('kundennr'), null=True, blank=True)

    @classmethod
    def hub(cls):
        """ Returns the Owner Abraxas - must have the key "ABX"    """
        if not cls.__hub:
            try:
                cls.__hub = cls.objects.get(key=HUB_OWNER_KEY)
            except:
                cls.__hub = None
        return cls.__hub


class ContainerSystem(AbstractDatahubModel):
    """ ContainerSystem defines how the hub handels different activities like
        adding an area, adding an user, ...
    """
    class Meta:
        verbose_name = _("ContainerSystem")
        verbose_name_plural = _("ContainerSystems")

    DATABASE = 'DB'
    FILESTORAGE = 'FS'

    TYPE = {
        DATABASE: _("DataBase"),
        FILESTORAGE: _("FileStorage"),
    }

    owner = models.ForeignKey(
        to=Owner, on_delete=models.PROTECT, related_name='+',)
    key = models.CharField(_('key'), max_length=20, unique=True,)
    type = models.CharField(_('type'), max_length=2, choices=TYPE)
    connection = models.JSONField(_('Connection'), null=True,
                                  blank=True, help_text=_("Base information for connection like middleware"))
    area_add = models.TextField(_('area_add'), null=True,
                                blank=True, help_text=_("Script used to add an area to container"))
    user_add = models.TextField(_('user_add'), null=True,
                                blank=True, help_text=_("Script used to add a user to container"))
    user_del = models.TextField(_('user_del'), null=True,
                                blank=True, help_text=_("Script used to delete a user from container"))
    scope_add = models.TextField(_('scope_add'), null=True,
                                 blank=True, help_text=_("Script used to add a scope to container"))
    scope_del = models.TextField(_('scope_del'), null=True,
                                 blank=True, help_text=_("Script used to delete a scope from container"))
    user_to_scope = models.TextField(_('user_to_scope'), null=True,
                                     blank=True, help_text=_("Script used to link a user to a container"))
    user_from_scope = models.TextField(_('user_from_scope'), null=True,
                                       blank=True, help_text=_("Script used to unlink a user from a container"))


class Container(AbstractDatahubModel):
    """ Can contain data of multiple areas/application
        But we expect that every client wants to have his own containers

        TODO: implement methods add_scope, delete_scope using scripts from ContainerSystem
    """

    class Meta:
        verbose_name = _("Container")
        verbose_name_plural = _("Containers")
        ordering = ['key']
        permissions = [
            (PERMISSION_UPLOAD_TEMPLATES, "Is allowed to upload report templates"),
            (PERMISSION_DOWNLOAD_TEMPLATES,
             "Is allowed to download report templates"),
            (PERMISSION_DIRECT_ACCESS, "Is allowed connect to db and read data"),
        ]

    def __init__(self, *args, **kwargs):
        self.__schemas = None
        super().__init__(*args, **kwargs)

    owner = models.ForeignKey(
        to=Owner, on_delete=models.PROTECT, related_name='+',)
    key = models.CharField(_('key'), max_length=20, unique=True,)
    containersystem = models.ForeignKey(
        to=ContainerSystem, on_delete=models.PROTECT)
    connection = models.JSONField(_('Connection'), null=True,
                                  blank=True, help_text=_("To establish connection to container"))
    execute_scripts = models.BooleanField(_('execute_scripts'), null=False, default=False,
                                 help_text=_("Only if activated scripts will be executed"))


    def exec_filestorage(self, code, parms):
        """ Ausführen von Code im File Storage"""
        test = """
import os
# Create app path if not exists
app_path = os.path.join('{path}', '{app}')
if not os.path.exists(app_path):
    os.mkdir(app_path)
# Create area path if not exists
area_path = os.path.join(app_path, '{area}')
if not os.path.exists(area_path):
    os.mkdir(area_path)
# Create scope path if not exists
scope_path = os.path.join(area_path, '{scope}')
if not os.path.exists(scope_path):
    os.mkdir(scope_path)
"""     
        if code:
            formatted_code = code.format(**parms).strip()
            exec(formatted_code)

    def add_scope(self, area, scope_key):
        parms = {'app': area.application.key, 'area': area.key, 'scope': scope_key,}
        if self.connection:
            parms.update(self.connection)
        db_logger.info (
            f"{str(self):10} - Action:'{self.containersystem}.scope_add' - Parms: {parms}")
        if self.containersystem.type == ContainerSystem.FILESTORAGE:
            self.exec_filestorage(self.containersystem.scope_add, parms)

    def delete_scope(self, area, scope_key):
        parms = {'app': area.application.key,
                 'area': area.key, 'scope': scope_key}
        if self.connection:
            parms.update(self.connection)
        db_logger.info(
            f"{str(self):10} - Action:'{self.containersystem}.scope_delete' - Parms: {parms}")
        code = """
import os
# Create app path if not exists
app_path = os.path.join('{path}', '{app}')
area_path = os.path.join(app_path, '{area}')
scope_path = os.path.join(area_path, '{scope}')
if os.path.exists(scope_path):
    print('exists:', scope_path)
    if len(os.listdir(scope_path)) == 0:
        os.rmdir(scope_path)
"""

        if self.containersystem.type == ContainerSystem.FILESTORAGE:
            self.exec_filestorage(self.containersystem.scope_del, parms)

    def add_area(self, area, schemaname):
        parms = {'app': area.application.key,
                 'area': area.key, 'schema': schemaname}
        db_logger.info(
            f"{str(self):10} - Action:'{self.containersystem}.area_add' - Parms: {parms}")

    def add_user(self, user):
        parms = {'user': user.username}
        db_logger.info(
            f"{str(self):10} - Action:'{self.containersystem}.user_add' - Parms: {parms}")

    def delete_user(self, user):
        parms = {'user': user.username}
        db_logger.info(
            f"{str(self):10} - Action:'{self.containersystem}.user_delete' - Parms: {parms}")

    @property
    def __name(self):
        """ Returns a string used as identifier for connection """
        return str(self.id)

    def __connect(self):
        if not self.containersystem.type == 'DB':
            raise Exception(

maintenance/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <title>DATA-Hub Prototype</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <script src="https://kit.fontawesome.com/b93e436f24.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue-grey.css">
    <style>html,body,h1,h2,h3,h4,h5 {
            font-family: "Raleway", sans-serif
        }
    </style>
</head>

<script>
    function show(id) {
      var x = document.getElementById(id);
      if (x.style.display === "none") {
        x.style.display = "block";
      } else {
        x.style.display = "none";
      }
    }
</script>

<body class="w3-light-grey">

    <!-- Top container -->
    <div class="w3-bar w3-top w3-theme-d5 w3-large" style="z-index:4">
        <button class="w3-bar-item w3-button w3-hide-large w3-hover-none w3-hover-text-light-grey"
            onclick="w3_open();"><i class="fa fa-bars"></i>  Menu</button>
            <span class="w3-bar-item">DATA-Hub Prototype</span>
            <span class="w3-bar-item w3-right">Abraxas / DATA-Hub</span>
    </div>

    <!-- Sidebar/menu -->
    <nav class="w3-sidebar w3-collapse w3-white" style="z-index:3;width:300px;" id="mySidebar"><br>
        <div class="w3-container w3-row w3-theme">
            <div class="w3-col s8 w3-bar ">
                Welcome, 
                <br>{{request.user.first_name}} {{request.user.last_name}}
                <br>{% if request.user.use_areascope %}{{request.user.use_areascope}} {% endif %}
                <br>
                <div class="w3-dropdown-hover">
                    <a href="#" class="w3-bar-item w3-button"><i class="fa fa-user"></i></a>
                    <div class="w3-dropdown-content w3-bar-block w3-card-4">
                        {% for auser in all_users %}
                        <a href="{% url 'switch_user' auser.id %}" class="w3-bar-item w3-button" >{{auser.first_name}} {{auser.last_name}} </a> 
                        {% endfor %}
                    </div>
                </div>
            
                <a href="{% url 'setareascope' %}" class="w3-bar-item w3-button"><i class="fa fa-cog"></i></a>
            </div>
        </div>
        <hr>


        <div class="w3-container w3-theme">
            <h5>Reporting</h5>
        </div>
        <div class="w3-bar-block">
            <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-file fa-fw"></i> Order New Report (TBD)</a>
            <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-download fa-fw"></i> Download
                Results (TBD)</a>
        </div>


        <div class="w3-container w3-theme">
            <h5>Overview</h5>
        </div>
        <div class="w3-bar-block">
            <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black"
                onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i> Close Menu</a>
            <a href="{% url 'index' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-globe fa-fw"></i> My DATA-Hub</a>

        {% if user.is_staff %}

            {% if perms.organization.view_dashboard %}
                <a href="{% url 'dashboard' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-gauge-high fa-fw"></i> Dashboard</a>
            {% endif %}    

            {% if request.user.is_superuser %}    
            <a href="{% url 'check' %}"  class="w3-bar-item w3-button w3-padding"><i class="fa fa-stethoscope fa-fw"></i> Health Check</a>
            <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-up-down-left-right fa-fw"></i> Cross Reference (TBD)</a>
            {% endif %}    
            <div class="w3-container w3-theme">
                <h5>Maintenance</h5>
            </div>
            <div class="w3-bar-block">
            {% if perms.organization.add_application %}     
            <a href="{% url 'admin:organization_application_changelist' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-city fa-fw"></i>  Applications</a>
            {% endif %}
            {% if perms.organization.add_area %}     
            <a href="{% url 'admin:organization_area_changelist' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-building fa-fw"></i>  Areas</a>
            {% endif %}
            {% if perms.organization.add_areascope %}            
                <a href="{% url 'admin:organization_areascope_changelist' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-solid fa-layer-group"></i> Areascopes</a>
            {% endif %}
            {% if perms.organization.add_user %}            
                <a href="{% url 'admin:organization_user_changelist' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-users fa-fw"></i> Users</a>
            {% endif %}
            {% if perms.organization.add_container %}            
                <a href="/admin" class="w3-bar-item w3-button w3-padding"><i class="fa fa-database fa-fw"></i> Data Storage</a>
            {% endif %}
            {% if perms.organization.add_application %}     
            <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-share fa-fw"></i>  Migration (TBD)</a>
            {% endif %}
            {% if request.user.is_superuser %}     
            <a href="{% url 'load' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-upload fa-fw"></i>  Load AW Data</a>
            {% endif %}
    
        {% endif %}
        </div>
    </nav>


    <!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer"
        title="close side menu" id="myOverlay"></div>
    
    <div class="w3-main" style="margin-left:300px;margin-top:43px;">

        {% if messages %}
        <div class="w3-row-padding w3-margin-bottom">
            {% for message in messages %}
            <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
                <h3 class="w3-green">{{ message }}</h3>
                {% endif %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <h3 class="w3-red">{{ message }}</h3>
                {% endif %}
            </p>
            {% endfor %}
        </div>
        {% endif %}
        
        {% block body %}
        {% endblock %}
    
        <br><br>
        <!-- Footer -->
        <footer class="w3-container w3-padding-16 w3-theme-d5">
            <h4>Prototype for Concept Discussions</h4>
            <p>Powered by Team Data Science / Abraxas</p>
        </footer>
    </div>  
    
    <script>
        // Get the Sidebar
        var mySidebar = document.getElementById("mySidebar");

        // Get the DIV with overlay effect
        var overlayBg = document.getElementById("myOverlay");

        // Toggle between showing and hiding the sidebar, and add overlay effect
        function w3_open() {
            if (mySidebar.style.display === 'block') {
                mySidebar.style.display = 'none';
                overlayBg.style.display = "none";
            } else {
                mySidebar.style.display = 'block';
                overlayBg.style.display = "block";
            }
        }

        // Close the sidebar with the close button
        function w3_close() {
            mySidebar.style.display = "none";
            overlayBg.style.display = "none";
        }
    </script>

</body>

</html>

maintenance/templates/check.html
{% extends 'base.html' %}

{% block body %}

<header class="w3-container" style="padding-top:22px">
    <h2><i class="fa fa-stethoscope fa-fw"></i> Health Check
        {% if owner %}of {{owner.desc}} ({{owner}}) {% endif %}
    </h2>
</header>
<br>

<h3>Databases - Connections</h3>
<table  class="w3-table-all">
<tr><th>Database</th><th>Description</th><th>Container Type</th><th>Connection</th><th>Information</th></tr>
{% for db, x in health_dbs.items %}
{% if db.active %}
    <tr>
        <td><a href="{% url 'admin:organization_container_change' db.id %}">{{db}}</a>
        <td>{{db.desc}}</td>
        <td><a href="{% url 'admin:organization_containersystem_change' db.containersystem.id %}">{{db.containersystem.key}}</a></td>
        <td>{{db.connection}}</td>
        <td>{% autoescape off %}{{x.badge_x}}{% endautoescape %} - {{x.msg_x}}</td>
    </tr>
{% endif %}
{% endfor %}
</table>

<h3>Areas - Schemas</h3>
<table  class="w3-table-all">
<tr><th>Application</th><th>Description (-> Check)</th><th>Area</th><th>RLS-Scipt</th><th>Description</th><th>Database</th><th>Table Schema</th><th>View Schema</th></tr>
{% for area, x in health_areas.items%}
{% if area.application.active %}
{% if area.active %}
    <tr>
        <td><a href="{% url 'admin:organization_application_change' area.application.id %}">{{area.application}}</a></td>
        <td><a href="{% url 'checkapplication' area.application.id %}">{{area.application.desc}}</a></td>
        <td><a href="{% url 'admin:organization_area_change' area.id %}">{{area.key}}</a></td>
        <td><a href="{% url 'area_rls' area.id %}">download</a></td>
        <td>{{area.desc}}</td>
        <td><a href="{% url 'admin:organization_container_change' area.database.id %}">{{area.database}}</a></td>
        {% if x.ok %}
            <td>{% autoescape off %}{{x.badge_t}}{% endautoescape %} - {{x.msg_t}}</td>
        {% else %}
            <td>{% autoescape off %}{{x.badge_t}}{% endautoescape %} - {{x.msg_t}}</td>
        {% endif %}
        <td>{% autoescape off %}{{x.badge_v}}{% endautoescape %} - {{x.msg_v}}</td>
    </tr>
{% endif %}
{% endif %}
{% endfor %}
</table>
{% if health_schemas %}
    <h1>Number of Tables of Schema "{{health_schemas.schema}}" in Area "{{health_schemas.area.application}} {{health_schemas.area}}": 
    {{health_schemas.number}}</h1>
    Check table if they have columns of the business unit types 
    {{health_schemas.area.application.business_unit_1}}  
    {{health_schemas.area.application.business_unit_2}}
    {{health_schemas.area.application.business_unit_3}}
{% endif %}



{% endblock %}

maintenance/templates/client.html
{% extends 'base.html' %}

{% block body %}
  
<h2 >Client: <a href="{% url 'admin:organization_client_change' client.id %}">{{client}}</a> - {{client.desc}}</h2>

<h3>Container</h3>
<ul>{% for container in client.container_set.all %}
    <li><b><a href="{% url 'admin:organization_container_change' container.id %}">{{container}}</a></b> ({{container.containertype}})</li>
    {% endfor %}
</ul>

<h3>Applications</h3>
<ul>{% for application in client.application_set.all %}
<li><b><a href="{% url 'admin:organization_application_change' application.id %}">{{application}}</a></b> {{application.desc}}
    / BUs: 
    {{application.business_unit_1}} 
    {% if application.business_unit_2 %} , {{application.business_unit_2}} {% endif %}
    {% if application.business_unit_3 %} , {{application.business_unit_3}} {% endif %}
    {% if application.business_unit_4 %} , {{application.business_unit_4}} {% endif %}
    {% if application.business_unit_5 %} , {{application.business_unit_5}} {% endif %}

    <ul><li>Areas:</li>
        <ul>{% for area in application.area_set.all %}
        <li><b><a href="{% url 'admin:organization_area_change' area.id %}">{{area}}</a></b> ({{area.desc}})
            with Database: <b><a href="{% url 'admin:organization_container_change' area.database.id %}">{{area.database}}</a></b> ({{area.database.desc}});
            Schema for user acces: <b>{{area.application.key.lower}}_{{area.key.lower}}</b>; 
            Schema for tables: <b>{{area.application.key.lower}}_{{area.key.lower}}_base</b>
            <br>
            with Filestorage: <b><a href="{% url 'admin:organization_container_change' area.filestorage.id %}">{{area.filestorage}}</a></b> ({{area.filestorage.desc}});
        </li>
        {% endfor area %}
    </ul>

    <li>Scopes = MinIo Buckets or Folder in Filesystem and RLS in DBs:</li>
    <ul>{% for scope in application.scope_set.all %}
        <li><b><a href="{% url 'admin:organization_scope_change' scope.id %}">{{scope}}</a> {{scope.desc}} </b>
            org: <b><a href="{% url 'admin:organization_scope_change' scope.org_scope_id %}">{{scope.org_scope}}</a></b> {{scope.org_scope.desc}}
            app: <b><a href="{% url 'admin:organization_scope_change' scope.app_scope_id %}">{{scope.app_scope}}</a></b> {{scope.app_scope.desc}}
        </li>
        {% endfor scope %}
    </ul>

</ul>
{% endfor application %}
</ul>

<h3>User</hr>
<ul>{% for user in client.user_set.all %}
    <li><b>
        <a href="{% url 'admin:organization_user_change' user.id %}">{{user}}</a></b> {{user.first_name}} {{user.last_name}}
        ({% for grp in user.groups.all %}
            <a href="{% url 'admin:organization_group_change' grp.id %}">{{grp}}</a>,
        {% endfor %})
        with access to scopes:
        ({% for scope in user.scopes.all %}
            <a href="{% url 'admin:organization_scope_change' scope.id %}">{{scope}}</a>,  
        {% endfor %})
        / <a href="{% url 'user' user.id %}">DETAILS</a> 
    </li>
{% endfor user %}
</ul>

{% endblock %}

maintenance/templates/dashboard.html
{% extends 'base.html' %}

{% block body %}

<header class="w3-container" style="padding-top:22px">
    <h2><i class="fa fa-gauge-high fa-fw"></i> Dashboard for {{owner}} - {{owner.desc}} (TBD)
        {% if application %}
        / {{application.key}} - {{application.desc}}
        {% endif %}
    </b></h2>
</header>

<div class="w3-row-padding w3-margin-bottom">
    <div class="w3-quarter">
        <div class="w3-container w3-theme w3-padding-16">
            <div class="w3-left"><i class="fa fa-city w3-xxxlarge"></i></div> 
            <div class="w3-right">
                <h3>{{owner.application_set.all|length}}/{{number_areas}}</h3>
            </div>
            <div class="w3-clear"></div>
            <h4>Applications / Areas </h4>
        </div>
    </div>
    <div class="w3-quarter">
        <div class="w3-container w3-theme w3-padding-16">
            <div class="w3-left"><i class="fa fa-solid fa-layer-group w3-xxxlarge"></i></div>
            <div class="w3-right">
                <h3>{{number_scopes}}</h3>
            </div>
            <div class="w3-clear"></div>
            <h4>Scopes</h4>
        </div>
    </div>
    <div class="w3-quarter">
        <div class="w3-container w3-theme w3-padding-16">
            <div class="w3-left"><i class="fa fa-users w3-xxxlarge"></i></div>
            <div class="w3-right">
                <h3>{{owner.user_set.all|length}}</h3>
            </div>
            <div class="w3-clear"></div>
            <h4>Users</h4>
        </div>
    </div>
    <div class="w3-quarter">
        <div class="w3-container w3-theme w3-padding-16">
            <div class="w3-left"><i class="fa fa-solid fa-file w3-xxxlarge"></i></div>
            <div class="w3-right">
                <h3>99</h3>
            </div>
            <div class="w3-clear"></div>
            <h4>Ordered Reports</h4>
        </div>
    </div>

</div>

<hr>
<div class="w3-container w3-padding">
    <h4>Data Load Statistics</h4>
    <div class="w3-half w3-padding">
        <h5>Today</h5>
        <p>Tables loaded</p>
        <div class="w3-grey">
            <div class="w3-container w3-center w3-padding w3-green" style="width:85%">85%</div>
        </div>
    </div>
</div>
<div class="w3-container w3-padding">
    <h4>Report Statistics / Compared to Average</h4>

    <div class="w3-half w3-padding">
        <h5>Today</h5>
        <p>Ordered Reports</p>
        <div class="w3-grey">
            <div class="w3-container w3-center w3-padding w3-green" style="width:22%">22%</div>
        </div>
        <p>Execution Time</p>
        <div class="w3-grey">
            <div class="w3-container w3-center w3-padding w3-orange" style="width:80%">80%</div>
        </div>
        <p>Reports in Error State</p>
        <div class="w3-grey">
            <div class="w3-container w3-center w3-padding w3-red" style="width:2%">2%</div>
        </div>
    </div>
    <div class="w3-half w3-padding">
        <h5>Last 7 Days</h5>
        <p>Ordered Reports</p>
        <div class="w3-grey">
            <div class="w3-container w3-center w3-padding w3-green" style="width:80%">80%</div>
        </div>
        <p>Execution Time</p>
        <div class="w3-grey">
            <div class="w3-container w3-center w3-padding w3-orange" style="width:90%">90%</div>
        </div>
        <p>Reports in Error State</p>
        <div class="w3-grey">
            <div class="w3-container w3-center w3-padding w3-red" style="width:1%">1%</div>
        </div>
    </div>


</div>
<hr>

{% endblock %}